os: Visual Studio 2015

environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: Wp85FZ3/lEWE9gP+vsr/4/CEhVnS3ApcGRcOWNlSGdYxjvQ07/LyiHOioY687n8l

  matrix:
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 8

platform:
  - x86
  - x64

configuration:
  - Release

install:
  - cmd: SET PUBLISH_BINARY=false
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('[publish binary]')) { $env:PUBLISH_BINARY=true }
  - cmd: ECHO %PUBLISH_BINARY%
  - cmd: IF %PUBLISH_BINARY%==true node-pre-gyp package 2>&1
  - cmd: IF %PUBLISH_BINARY%==true node-pre-gyp-github publish --release 2>&1
  - cmd: IF %PUBLISH_BINARY%==true node-pre-gyp clean

build: OFF
test: OFF
deploy: OFF